### ISSUE TITLE
Feature: WASM Support

### ISSUE THREAD

**Issue by Maxxen** [duckdb/duckdb_spatial#17]
Now that extension loading in WASM is coming along it would be great if we could run this extension in WASM.
I think the main blocker right now is the fact that we compile GDAL with libcurl and openssl, but once #15 this should be easy. Alternatively we could add a compile flag to disable the networked GDAL functionality when compiling on emscripten.

Additionally we may want to support some additional output/conversion formats common in web, like GeoJSON, MVT or GeoArrow.

**Comment by carlopi** [comment]
Brief update: very experimental version of spatial.extension.wasm has been compiled!

Build script needed minor rework to remove openssl and libcurl (but neither should impact capabilities since the browser/JS engine will perform encryption for you), but all major components are now included [thanks @Maxxen for the guidance all around].
I'd say #15 is not a blocker for Web deployment.

Functionality seems to be there, but more structured testing is on the todo list to ensure feature parity.

Extension loading is currently in an experimental stage itself, but making steady progress, very much looking forward to duckdb_spatial support for the Web.

**Comment by carlopi** [comment]
It' actually up!

https://shell.duckdb.org

then
```
LOAD spatial;
SELECT * EXCLUDE full_geom FROM (SELECT borough, st_union_agg(geom) as full_geom, st_area(full_geom) as area, st_centroid(full_geom)::string as centroid, count(*) as count FROM st_read('https://raw.githubusercontent.com/duckdb/duckdb_spatial/main/test/data/nyc_taxi/taxi_zones/taxi_zones.shp') GROUP BY borough);
```

Thanks a lot @Maxxen for supporting this, exiting times.
