### ISSUE TITLE
Core dumped when selecting all after loading csv

### ISSUE THREAD

**Issue by cuteDen-ECNU** [duckdb/duckdb_spatial#171]
Core dumped when using this statement:
```
CREATE TABLE origin As SELECT * FROM read_csv('/script/1.csv', delim=',', header=true, columns={'id': 'Integer', 'geom': 'geometry'});
SELECT * FROM origin;
-- terminate called after throwing an instance of 'duckdb::SerializationException'
--  what():  Serialization Error: Trying to read past end of buffer
-- Aborted (core dumped)
```
csv file:
```
id,geom
0,"POLYGON EMPTY"
```

Version information:
v0.9.2-dev209 6545a55cfe

**Comment by Maxxen** [comment]
Hi! Thanks for filing this issue. This is reproducible on 0.9.1 by just doing `SELECT 'POINT(1 2)'::GEOMETRY;`.

The problem is that since `GEOMETRY` is technically a `BLOB` and `VARCHAR` can always cast to `BLOB` by just reinterpreting the bytes, you end up with a invalid geometry blob which then can't be deserialized when you try to print the result to the CLI. 

What we should do instead is to implement an explicit `VARCHAR`->`GEOMETRY` that either errors or does the `ST_GeomFromText` conversion internally to avoid accidentally converting `VARCHAR`->`BLOB`->`GEOMETRY`

The crash is caused by exceptions that are thrown inside extension not being catchable by DuckDB due to the dynamically loaded extensions and duckdb core having different run-time type information, which some libc++ implementations use to identify exception types. This is a known long standing issue, see e.g. https://github.com/duckdb/duckdb/issues/6521

**Comment by cuteDen-ECNU** [comment]
Thanks for clarifying the usage! I will update my script.^^
