### ISSUE TITLE
LINESTRING EMPTY crashes duckdb spatial.

### ISSUE THREAD

**Issue by cuteDen-ECNU** [duckdb/duckdb_spatial#195]
Hi, the following statement crashes duckdb spatial.
```sql
SELECT ST_PointOnSurface(ST_Collect([ST_GeomFromText('LINESTRING(0 0, 1 1)'), ST_GeomFromText('LINESTRING EMPTY')]))
--Segmentation fault (core dumped)
```

Using the function ST_AsText, I got the following result.
```sql
SELECT ST_AsText(ST_Collect([ST_GeomFromText('LINESTRING(0 0, 1 1)'), ST_GeomFromText('LINESTRING EMPTY')]))
-- [('MULTILINESTRING ((0 0, 1 1), ())',)]
```

Version:

The result of "pragma version;" is [('v0.9.2', '3c695d7ba9')]

I used "FORCE INSTALL spatial FROM 'http://nightly-extensions.duckdb.org';" in the Python client.

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue! Testing with PostGIS it seems to crash there too! 
Thankfully the fix is easy, we just need to check if the geometry is empty before we push it to the collection here:

https://github.com/duckdb/duckdb_spatial/blob/d3f53329f176be13fb9ea1dc3b1fe3feab35167e/spatial/src/spatial/core/functions/scalar/st_collect.cpp#L32-L34

Will include a fix next push!
