### ISSUE TITLE
Understand an error message

### ISSUE THREAD

**Issue by aborruso** [duckdb/duckdb_spatial#250]
Hi, when I run

```
duckdb -c "COPY (SELECT * EXCLUDE geom, ST_GeomFromWKB(geom) AS geometry from st_read('input.shp')) TO 'tmp.parquet' WITH (FORMAT PARQUET)"
```

I have 

```
Error: Not implemented Error: Geometry type '19460' not supported
```

What's "Geometry type '19460'"? How can I make sure to overcome this problem and turn my shp into parquet?

Thank uou

**Comment by Maxxen** [comment]
The issue is that you are trying to covert a blob that already is GEOMETRY from WKB to GEOMETRY. The internal binary format is different between the two which is why ST_GeomFromWKB produces this strange error (it doesn't understand the bytes). 

You do not need to convert the geometry from WKB anymore since v0.9.2, st_read produces GEOMETRY now by default.

**Comment by Maxxen** [comment]
However when storing it in parquet you probably want to encode it as WKB, so you should just change the ST_GeomFromWKB to ST_AsWKB

**Comment by aborruso** [comment]
> You do not need to convert the geometry from WKB anymore since v0.9.2, st_read produces GEOMETRY now by default.

Then is it necessary to edit the "[Example Usage](https://github.com/duckdb/duckdb_spatial#example-usage)" section in the README, because the `taxi_zones` field is already a geometry field?

**Comment by Maxxen** [comment]
Yes, The README here is super outdated and will hopefully be replaced woth somethibg better next release
