### ISSUE TITLE
ST_Transform - wrong transformation

### ISSUE THREAD

**Issue by zabojpetr** [duckdb/duckdb_spatial#286]
Hi,

I needed to transform shapefile from WGS84 (EPSG:4326) to Krovak (EPSG:5514) and I find out that a result of the transformation is wrong. See the image from QGIS - green one is original and red one is transformed
![obrazek](https://github.com/duckdb/duckdb_spatial/assets/6089349/f175238d-9172-4a14-936e-d391135be8e6)

I tried it with JDBC driver and Python API both in version 0.10.0.

The SQL used

```sql
SELECT 
    ST_AsText(geom) as geom, 
    ST_AsText(ST_Transform(geom, 'EPSG:4326', 'EPSG:5514')) as krovak 
FROM 
    ST_read("hex/hex_9_square.shp") as hex_9
```

**Comment by Maxxen** [comment]
Hi! Thanks for reporting this issue!

DuckDB spatial in comparison to most other GIS tools currently tries to follow the axis order mandated by the projection, which in the case of 'EPSG:4326' is latitude/longitude, _not_ longitude/latitude. We have plans to change this in the future so that all geometries and functions expect Lon/Lat regardless of what projection you are working with, but for now you probably want to experiment with setting the `always_xy := <bool>` optional argument to `ST_Transform` or use `ST_FlipCoordinates` before/after projecting.

**Comment by zabojpetr** [comment]
Thank you for quick response. 

Both options works well!
Unfortunetly I didn't find any documentation to the optional parameter `always_xy`. Is there somewhere?
But of course `ST_FlipCoordinates` is more explicit and clear.

```sql
SELECT 
    ST_AsText(geom) as geom, 
    ST_AsText(ST_Transform(ST_FlipCoordinates(hex_9.geom), 'EPSG:4326', 'EPSG:5514')) AS krovak,
    ST_AsText(ST_Transform(hex_9.geom, 'EPSG:4326', 'EPSG:5514', True)) AS krovak2
FROM 
    ST_read("hex/hex_9_square.shp") as hex_9 
```

**Comment by Maxxen** [comment]
The new docs are still a bit rough around the edges but I've attempted to document this better here: . https://github.com/duckdb/duckdb_spatial/blob/main/docs/functions.md#st_transform
