### ISSUE TITLE
The command "ST_Multi" is not recognized as a valid command. 

### ISSUE THREAD

**Issue by LucasPaganiniRM** [duckdb/duckdb_spatial#408]
When I try to convert a Polygon to a MultiPolygon type using DuckDB, the output claims that the command ST_Multi(geometry) doesn't exist, even though this command is present in the official DuckDB documentation.

Here is the input:
```
SELECT ST_Multi(geom)
FROM mesclar_atualizados
```

And this is the output I get:
```
CatalogException: Catalog Error: Scalar Function with name st_multi does not exist!
Did you mean "str_split"?
```

**Comment by Maxxen** [comment]
ST_Multi is not present in v1.1.0 but will be in v.1.1.1 that should release later today. I added `ST_Multi` to the latest dev-version of the documentation but I guess because it is a minor release (and technically a bug fix release) it gets grouped under `v1.1 (stable)` in the docs. I'll bring that up internally, maybe we can make it clearer.
