### ISSUE TITLE
Internal error: calling StringValue::Get on a NULL value

### ISSUE THREAD

**Issue by cboettig** [duckdb/duckdb_spatial#426]
### What happens?

Reporting an internal error as [directed](https://duckdb.org/docs/dev/internal_errors).  The code below produces the error 

```
InternalException: INTERNAL Error: Calling StringValue::Get on a NULL value
```

### To Reproduce

```
import duckdb
conn = duckdb.connect()
conn.sql('''
INSTALL spatial;
LOAD spatial; 
COPY (SELECT * from read_parquet('https://huggingface.co/datasets/boettiger-lab/ca-30x30/resolve/main/ca2024.parquet') )
TO 'ca2024.fgb' WITH (FORMAT GDAL, DRIVER 'flatgeobuf');
''')
```

### OS:

Ubuntu

### DuckDB Version:

1.1.1

### DuckDB Client:

python

### Full Name:

Carl Boettiger

### Affiliation:

UC Berkeley

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Maxxen** [comment]
So, I had a look at this and indeed there's an issue on our end where we don't check for NULL geometries properly. I have a fix in progress, but even with it applied the query still fails because unfortunately there is an underlying issue in that flatgeobuf does not support writing FGB spatial indexes when some geometries are NULL. [This is a known limitation documented by GDAL](https://gdal.org/en/latest/drivers/vector/flatgeobuf.html#creation-issues), also [discussed here](https://github.com/flatgeobuf/flatgeobuf/discussions/260)

Once my fix is merged you can work around it by adding the `SPATIAL_INDEX=NO` layer creation option, e.g.
```
COPY (SELECT * from read_parquet('https://huggingface.co/datasets/boettiger-lab/ca-30x30/resolve/main/ca2024.parquet') )
  TO 'ca2024.fgb' WITH (FORMAT GDAL, DRIVER 'flatgeobuf', LAYER_CREATION_OPTIONS ('SPATIAL_INDEX=NO'));
 ```
